export const SALES_RETURNS_LABELS = {
  paidFrom: "Paid from",
  paidFromRequired: "Paid from is required",
  payeeSection: "Payee",
  payeeRequired: "Payee is required",
  payeePlaceholder: "Payee name",
  gridPaidFrom: "Paid From",
  gridPayee: "Payee",
  pageTitle: "Sales Returns",
  pageSubtitle: "Record and manage sales return transactions",
  exportFileName: "Sales Returns",
  addFormTitle: "Add New Sales Return",
  editFormTitle: "Edit Sales Return",
  deleteConfirm: "Are you sure you want to delete this sales return?",
  noAttachments: "No attachments for this sales return.",
};

export const COLLECTIONS_LABELS = {
  paidFrom: "Paid from",
  paidFromRequired: "Paid from is required",
  payeeSection: "Payee",
  payeeRequired: "Payee is required",
  payeePlaceholder: "Payee name",
  gridPaidFrom: "Paid From",
  gridPayee: "Payee",
  pageTitle: "Collections",
  pageSubtitle: "Record and manage collection transactions",
  exportFileName: "Collections",
  addFormTitle: "Add New Collection",
  editFormTitle: "Edit Collection",
  deleteConfirm: "Are you sure you want to delete this collection?",
  noAttachments: "No attachments for this collection.",
};

export const SHARE_DISTRIBUTIONS_LABELS = {
  paidFrom: "Paid from",
  paidFromRequired: "Paid from is required",
  payeeSection: "Payee",
  payeeRequired: "Payee is required",
  payeePlaceholder: "Payee name",
  gridPaidFrom: "Paid From",
  gridPayee: "Payee",
  pageTitle: "Share Distributions",
  pageSubtitle: "Record and manage share distribution transactions",
  exportFileName: "Share Distributions",
  addFormTitle: "Add New Share Distribution",
  editFormTitle: "Edit Share Distribution",
  deleteConfirm: "Are you sure you want to delete this share distribution?",
  noAttachments: "No attachments for this share distribution.",
};
