export const PAYMENTS_LABELS = {
  paidFrom: "Paid From",
  paidFromRequired: "Paid From is required",
  receivedFromRequired: "Paid From is required",
  payeeSection: "Party Type",
  payeeRequired: "Paid To is required",
  payeePlaceholder: "Paid To",
  partyType: "Party Type",
  vrNo: "Vr No",
  vrNoRequired: "Vr No is required",
  gridPaidFrom: "Paid From",
  gridPayee: "Paid To",
  gridVrNo: "Vr No",
  gridPartyType: "Party Type",
  pageTitle: "Payments",
  pageSubtitle: "Record and manage payment transactions",
  exportFileName: "Payments",
  addFormTitle: "Add New Payment",
  editFormTitle: "Edit Payment",
  viewFormTitle: "View Payment",
  deleteConfirm: "Are you sure you want to delete this payment?",
  noAttachments: "No attachments for this payment.",
};

export const RECEIPTS_LABELS = {
  paidFrom: "Paid By",
  paidFromRequired: "Paid By is required",
  payeeSection: "Received In",
  payeeRequired: "Received In is required",
  payeePlaceholder: "Received In name",
  gridPaidFrom: "Paid By",
  gridPayee: "Received In",
  pageTitle: "Receipts",
  pageSubtitle: "Record and manage receipt transactions",
  exportFileName: "Receipts",
  addFormTitle: "Add New Receipt",
  editFormTitle: "Edit Receipt",
  viewFormTitle: "View Receipt",
  deleteConfirm: "Are you sure you want to delete this receipt?",
  noAttachments: "No attachments for this receipt.",
  tabPendingAhq: "Pending AHQ approval",
  tabFinalizedAhq: "Finalized by AHQ",
};
